begin;
select set_config('qa.admin',gen_random_uuid()::text,true),set_config('qa.student',gen_random_uuid()::text,true),set_config('qa.other',gen_random_uuid()::text,true),set_config('qa.cycle',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting(k)::uuid,'qa-'||current_setting(k)||'@example.invalid','{"name":"QA temporário"}'::jsonb from unnest(array['qa.admin','qa.student','qa.other']) k;
update public.profiles set active=true,plan='Estratégico',role=case when id=current_setting('qa.admin')::uuid then 'admin' else 'student' end where id in (current_setting('qa.admin')::uuid,current_setting('qa.student')::uuid,current_setting('qa.other')::uuid);
select set_config('request.jwt.claim.sub',current_setting('qa.admin'),true);
set local role authenticated;
insert into public.cycles(id,student_id,title,status,start_date,duration_days,blocks) values(current_setting('qa.cycle')::uuid,current_setting('qa.student')::uuid,'QA ciclo','Publicado','2026-01-01',30,'[{"id":"b1","date":"2026-01-01","subject":"Matemática","topic":"MMC e MDC","topic_key":"CFO|Matemática|1","minutes":60}]');
select set_config('qa.question',public.save_question('{"subject":"QA","topic":"QA","difficulty":"Média","body":"Enunciado original","options":["A","B"],"correct_index":0,"explanation":"Comentário original"}')::text,true);
with ex as(insert into public.exams(title,duration,question_ids) values('QA Simulado',10,array[current_setting('qa.question')::uuid]) returning id) select set_config('qa.exam',id::text,true) from ex;
insert into public.question_comments(question_id,student_id,body) values(current_setting('qa.question')::uuid,auth.uid(),'Comentário com gabarito');
do $$ begin if jsonb_array_length(public.get_exam_print(current_setting('qa.exam')::uuid)->'questions')<>1 then raise exception 'Admin não imprimiu';end if;end;$$;
reset role;
select set_config('request.jwt.claim.sub',current_setting('qa.student'),true);
set local role authenticated;
do $$ declare res jsonb;begin
 if exists(select 1 from public.method_templates) then raise exception 'Aluno leu modelos administrativos';end if;
 perform public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','study'));
 perform public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','study'));
 if (select count(*) from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid)<>4 then raise exception 'Revisões duplicadas';end if;
 if (select array_agg(due_day order by due_day) from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid)<>array[2,4,8,15] then raise exception 'Intervalos incorretos';end if;
 if not exists(select 1 from public.progress where student_id=auth.uid() and key='edital|CFO|Matemática|1' and flags->>'study'='true') then raise exception 'Edital não atualizado';end if;
 begin perform public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','questions','total',5,'correct',4,'understanding','bem'));raise exception using errcode='XX000',message='Aceitou menos que mínimo';exception when raise_exception then if sqlerrm not like '%ao menos%' then raise;end if;end;
 res:=public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','questions','total',10,'correct',5,'understanding','dificuldade','notes','Preciso retomar'));
 perform public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','questions','total',10,'correct',5,'understanding','dificuldade'));
 if (select count(*) from public.study_logs where method_study_id is not null and student_id=auth.uid())<>1 then raise exception 'Resultado duplicado';end if;
 if (select count(*) from public.method_reviews where extra and cycle_id=current_setting('qa.cycle')::uuid)<>1 then raise exception 'Reforço ausente ou duplicado';end if;
 if (public.advance_method_day(current_setting('qa.cycle')::uuid)->>'day')::integer<>2 then raise exception 'Dia não avançou';end if;
 begin perform public.advance_method_day(current_setting('qa.cycle')::uuid);raise exception using errcode='XX000',message='Avançou com revisão pendente';exception when raise_exception then if sqlerrm not like '%revisões pendentes%' then raise;end if;end;
 perform public.record_method_action(jsonb_build_object('action','review','review_id',(select id from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid and due_day=2),'total',5,'correct',4,'understanding','bem'));
 if (public.advance_method_day(current_setting('qa.cycle')::uuid)->>'day')::integer<>3 then raise exception 'Revisão não foi concluída';end if;
 begin perform public.get_exam_print(current_setting('qa.exam')::uuid);raise exception using errcode='XX000',message='Impressão liberou antes';exception when raise_exception then if sqlerrm not like '%Finalize%' then raise;end if;end;
 begin perform public.answer_question(current_setting('qa.question')::uuid,0);raise exception using errcode='XX000',message='Banco vazou gabarito';exception when raise_exception then if sqlerrm not like '%Finalize%' then raise;end if;end;
 if exists(select 1 from public.question_comments where question_id=current_setting('qa.question')::uuid) then raise exception 'Comentário vazou gabarito';end if;
 res:=public.start_exam(current_setting('qa.exam')::uuid);perform set_config('qa.attempt',res->>'id',true);
 if res->'questions'->0 ? 'correct_index' or res->'questions'->0 ? 'explanation' then raise exception 'Snapshot expôs gabarito';end if;
 if res->'questions'->0->>'body'<>'Enunciado original' then raise exception 'Enunciado ausente';end if;
 if public.start_exam(current_setting('qa.exam')::uuid)->>'id'<>current_setting('qa.attempt') then raise exception 'Início duplicou tentativa';end if;
 perform public.save_exam_answer(current_setting('qa.attempt')::uuid,current_setting('qa.question')::uuid,0);
end;$$;
reset role;
select set_config('request.jwt.claim.sub',current_setting('qa.other'),true);
set local role authenticated;
do $$ begin
 if exists(select 1 from public.method_reviews where student_id=current_setting('qa.student')::uuid) then raise exception 'Acesso aos dados de outro aluno';end if;
 begin perform public.record_method_action(jsonb_build_object('cycle_id',current_setting('qa.cycle'),'block_id','b1','action','step','step_id','study'));raise exception using errcode='XX000',message='Escrita cruzada';exception when raise_exception then if sqlerrm not like '%Ciclo não encontrado%' then raise;end if;end;
 begin perform public.submit_exam(current_setting('qa.attempt')::uuid,'{}');raise exception using errcode='XX000',message='Corrigiu tentativa alheia';exception when raise_exception then if sqlerrm not like '%Tentativa não encontrada%' then raise;end if;end;
end;$$;
reset role;
select set_config('request.jwt.claim.sub',current_setting('qa.admin'),true);
set local role authenticated;
do $$ declare rid uuid;begin
 select id into rid from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid and extra;
 perform public.manage_method_review(jsonb_build_object('action','cancel','review_id',rid));
 update public.cycles set blocks=jsonb_set(blocks,'{0,method,reviews}','[{"id":"r1","after":3,"questions":5},{"id":"r2","after":7,"questions":5},{"id":"r3","after":15,"questions":7},{"id":"r4","after":30,"questions":10}]') where id=current_setting('qa.cycle')::uuid;
 if (select due_day from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid and review_key='r2')<>8 then raise exception 'Revisão pendente não reagendou';end if;
 if (select due_day from public.method_reviews where cycle_id=current_setting('qa.cycle')::uuid and review_key='r1')<>2 then raise exception 'Mudou revisão concluída';end if;
 if not exists(select 1 from public.method_reviews where id=rid and status='cancelled') then raise exception 'Recriou reforço cancelado';end if;
 perform public.save_question(jsonb_build_object('id',current_setting('qa.question'),'subject','QA','topic','QA','difficulty','Média','body','Enunciado alterado','options',jsonb_build_array('X','Y'),'correct_index',1,'explanation','Comentário novo'));
end;$$;
reset role;
update public.exam_attempts set deadline=now()-interval '1 second' where id=current_setting('qa.attempt')::uuid;
select set_config('request.jwt.claim.sub',current_setting('qa.student'),true);
set local role authenticated;
do $$ declare res jsonb;begin
 res:=public.submit_exam(current_setting('qa.attempt')::uuid,jsonb_build_object(current_setting('qa.question'),1));
 if res->>'score'<>'1' or res->'details'->0->>'explanation'<>'Comentário original' then raise exception 'Gabarito snapshot ou resposta salva incorretos';end if;
 perform public.submit_exam(current_setting('qa.attempt')::uuid,'{}');
 if (select count(*) from public.study_logs where student_id=auth.uid() and origin='exam')<>1 then raise exception 'Correção duplicou desempenho';end if;
 if not exists(select 1 from public.question_comments where question_id=current_setting('qa.question')::uuid) then raise exception 'Comentários não liberados após finalizar';end if;
 res:=public.get_exam_print(current_setting('qa.exam')::uuid);
 if res->'questions'->0->>'body'<>'Enunciado original' or res->'questions'->0->>'explanation'<>'Comentário original' then raise exception 'Impressão não preservou simulado respondido';end if;
end;$$;
reset role;
select 'PASS: revisões, idempotência, limites, reforço, edição, dias, permissões, gabarito, impressão e snapshots' as result;
rollback;
